baseurl = "http://www.gl-li.com/"
languageCode = "en-us"
title = "R & Census"
theme = "blackburn"
author = "GL Li"
copyright = "&copy; 2017 - 2019. All rights reserved."
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
paginate = 20

[permalinks]
  post = "/:year/:month/:day/:slug/"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "explore census data with R"
  #brand = "![Simply Statistics Logo](/img/sslogo.png)"
  googleAnalytics = "UA-132163439-1"
  disqus = "gl-li-github-io"
  # CSS name for highlight.js
  highlightjs = "github"
  dateFormat = "2006/01/02"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  #[[menu.main]]
  #  name = "About"
  #  pre = "<i class='fa fa-user fa-fw'></i>"
  #  weight = 2
  #  identifier = "about"
  #  url = "/about/"
  [[menu.main]]
    name = "Archive"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 3
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "R-bloggers"
    pre = "<i class='fa fa-comments fa-fw'></i>"
    weight = 4
    url = "https://www.r-bloggers.com/"
  [[menu.main]]
    name = "R Weekly"
    pre = "<i class='fa fa-book fa-fw'></i>"
    weight = 5
    url = "https://rweekly.org/"
  [[menu.main]]
    name = "Census Blogs"
    pre = "<i class='fa fa-microphone fa-fw'></i>"
    weight = 6
    url = "https://www.census.gov/newsroom/blogs/about.html"


[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  twitter = "guanglai_li"
  facebook = ""
  instagram = ""
  github = "GL-Li"
  stackoverflow = ""
  linkedin = ""