baseurl = "/"
languageCode = "en-us"
title = "learneR & useR"
theme = "hugo-steam-theme"
disqusShortname = "gl-li-github-io"
# Enable Google Analytics be inserting your tracking code
googleAnalytics = ""
# Number of posts per page
paginate = 25

[params]
	title = "learneR & useR"
	subtitle = "well, it is learn R and use R"
	copyright = "Released under the MIT license."

	# You can choose between green, orange, red and blue.
	themecolor = "green"

	# Link custom assets relative to /static
	favicon   = "favicon.ico"
	customCSS = []
	customJS  = []

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "John Doe"
	bio = "programmer - blogger - coffee aficionado"
	description = "Your description of the blog"
	
	# Link your social networks (optional)
	location = ""
	twitter = "gl-li-github-io"
	linkedin = ""
	googleplus = ""
	facebook = ""
	instagram = ""
	github = "GL-Li"
	gitlab = ""
	bitbucket = ""

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"