

  
    
  


  




  


  

<!DOCTYPE html>
<html lang="en-us">
  <head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="generator" content="Hugo 0.31.1 with theme Tranquilpeak 0.4.3-BETA">
    <title>Extract US Census 2010 data with data.table and dplyr</title>
    <meta name="author" content="Firstname Lastname">
    <meta name="keywords" content="">

    <link rel="icon" href="/favicon.png">
    

    
    <meta name="description" content="This post explains how to extract information from the original dataset of the US 2010 census summary file 1 with urban/rural update, using data.table or dplyr package in R.
Why do we want to work with the original data? You may ask, when there are already R packages, such as UScensus2010, censusapi, and tidycensus, which help user get the data.
The biggest benefit is that you will have full access to all the census 2010 data.">
    <meta property="og:description" content="This post explains how to extract information from the original dataset of the US 2010 census summary file 1 with urban/rural update, using data.table or dplyr package in R.
Why do we want to work with the original data? You may ask, when there are already R packages, such as UScensus2010, censusapi, and tidycensus, which help user get the data.
The biggest benefit is that you will have full access to all the census 2010 data.">
    <meta property="og:type" content="blog">
    <meta property="og:title" content="Extract US Census 2010 data with data.table and dplyr">
    <meta property="og:url" content="/2017/08/process-2010-census-data-with-data-table/">
    <meta property="og:site_name" content="R &amp; Census">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:title" content="R &amp; Census">
    <meta name="twitter:description" content="This post explains how to extract information from the original dataset of the US 2010 census summary file 1 with urban/rural update, using data.table or dplyr package in R.
Why do we want to work with the original data? You may ask, when there are already R packages, such as UScensus2010, censusapi, and tidycensus, which help user get the data.
The biggest benefit is that you will have full access to all the census 2010 data.">
    
    

    
    

    
      <meta property="og:image" content="//www.gravatar.com/avatar/d09dc2d7aa5c467519e8af89f7b3d94c?s=640">
    

    
    
    

    

    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.4/jquery.fancybox.min.css" integrity="sha256-vuXZ9LGmmwtjqFX1F+EKin1ThZMub58gKULUyf0qECk=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.4/helpers/jquery.fancybox-thumbs.min.css" integrity="sha256-SEa4XYAHihTcEP1f5gARTB2K26Uk8PsndQYHQC1f4jU=" crossorigin="anonymous" />
    
    
    <link rel="stylesheet" href="/css/style-jsjn0006wyhpyzivf6yceb31gvpjatbcs3qzjvlumobfnugccvobqwxnnaj8.min.css" />
    
    

    
      
    
    
  </head>

  <body>
    <div id="blog">
      <header id="header" data-behavior="4">
  <i id="btn-open-sidebar" class="fa fa-lg fa-bars"></i>
  <div class="header-title">
    <a class="header-title-link" href="/">R &amp; Census</a>
  </div>
  
    
      <a class="header-right-picture "
         href="/#about">
    
    
    
      
        <img class="header-picture" src="//www.gravatar.com/avatar/d09dc2d7aa5c467519e8af89f7b3d94c?s=90" alt="Author&#39;s picture" />
      
    
    </a>
  
</header>

      <nav id="sidebar" data-behavior="4">
  <div class="sidebar-container">
    
      <div class="sidebar-profile">
        <a href="/#about">
          <img class="sidebar-profile-picture" src="//www.gravatar.com/avatar/d09dc2d7aa5c467519e8af89f7b3d94c?s=110" alt="Author&#39;s picture" />
        </a>
        <h4 class="sidebar-profile-name">Firstname Lastname</h4>
        
          <h5 class="sidebar-profile-bio">Super bio with markdown support <strong>COOL</strong></h5>
        
      </div>
    
    <ul class="sidebar-buttons">
      
  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="/">
    
      <i class="sidebar-button-icon fa fa-lg fa-home"></i>
      
      <span class="sidebar-button-desc">Home</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="/categories">
    
      <i class="sidebar-button-icon fa fa-lg fa-bookmark"></i>
      
      <span class="sidebar-button-desc">Categories</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="/tags">
    
      <i class="sidebar-button-icon fa fa-lg fa-tags"></i>
      
      <span class="sidebar-button-desc">Tags</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="/archives">
    
      <i class="sidebar-button-icon fa fa-lg fa-archive"></i>
      
      <span class="sidebar-button-desc">Archives</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="/#about">
    
      <i class="sidebar-button-icon fa fa-lg fa-question"></i>
      
      <span class="sidebar-button-desc">About</span>
    </a>
  </li>


    </ul>
    <ul class="sidebar-buttons">
      
  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="https://github.com/kakawait">
    
      <i class="sidebar-button-icon fa fa-lg fa-github"></i>
      
      <span class="sidebar-button-desc">GitHub</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="https://stackoverflow.com/users/636472/kakawait">
    
      <i class="sidebar-button-icon fa fa-lg fa-stack-overflow"></i>
      
      <span class="sidebar-button-desc">Stack Overflow</span>
    </a>
  </li>


    </ul>
    <ul class="sidebar-buttons">
      
  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="/index.xml">
    
      <i class="sidebar-button-icon fa fa-lg fa-rss"></i>
      
      <span class="sidebar-button-desc">RSS</span>
    </a>
  </li>


    </ul>
  </div>
</nav>

      

      <div id="main" data-behavior="4"
        class="
               hasCoverMetaIn
               ">
        <article class="post" itemscope itemType="http://schema.org/BlogPosting">
          
          
            <div class="post-header main-content-wrap text-left">
  
    <h1 class="post-title" itemprop="headline">
      Extract US Census 2010 data with data.table and dplyr
    </h1>
  
  
  <div class="postShorten-meta post-meta">
    
      <time itemprop="datePublished" datetime="2017-08-29T00:00:00Z">
        
  August 29, 2017

      </time>
    
    
  
  
    <span>in</span>
    
      <a class="category-link" href="/categories/data.table">data.table</a>
    
  

  </div>

</div>
          
          <div class="post-content markdown" itemprop="articleBody">
            <div class="main-content-wrap">
              <p>This post explains how to extract information from the original dataset of the US 2010 census summary file 1 with urban/rural update, using data.table or dplyr package in R.</p>
<p>Why do we want to work with the original data? You may ask, when there are already R packages, such as UScensus2010, censusapi, and tidycensus, which help user get the data.</p>
<p>The biggest benefit is that you will have full access to all the census 2010 data. The total size of the US 2010 national census summary 1 file with urban/rural update is nearly 150Gb, which is too heavy to be included as dataset in a package. The stand-alone UScensus2010 package only delivers selected demographic data. Others provide an access to United States Census Bureau’s APIs, which also offers selected data. By dealing with the original data directly, you can extract whatever data you want.</p>
<p>In recent years, fast development of packages data.table and dplyr makes it possible for R to process original 2010 census data in a reasonable time frame. In the following example, I retrieved the latitude, longitude, population of all race and of black people living in each census block in the city of South Bend Indiana. The whole process takes about 4 seconds on a four years old laptop. With these data in hand we can plot nicely where black people live down to census block level on a map downloaded from GoogleMap. In a city most census blocks are equivalent to street blocks.</p>
<p><img src="/post/2017-08-29-process-2010-census-data-with-data-table_files/figure-html/unnamed-chunk-2-1.png" width="768" /></p>
<p>This post is organized in this order: I will first give a brief introduction to the 2010 census summary file 1 with urban/rural update. Then I will show how to extract data step by step using R and data.table package with the example shown above. The codes are verbose in this section as I want to show the details. To clean it up I will then give a more concise codes that use pipe operator from magrittr package. As many users are more familiar with dplyr package, I will also translate the data.table code to dplyr code. The dplyr approach is sufficiently fast for most applications.</p>
<div id="file-structure-of-the-census-2010-summary-1-file" class="section level2">
<h2>File structure of the census 2010 summary 1 file</h2>
<p>The 2010 census data with urban/rural update can be downloaded from <a href="https://www2.census.gov/census_2010/04-Summary_File_1/Urban_Rural_Update/">United States Census Bureau official site</a>. The total size is nearly 150 GB so make sure you have enough hard drive space for it. The data is split into 50 states and DC. Click on a state, for example, Indiana, there is a file named in2010.ur1.zip. Download this file and unzip it to a folder named with the abbreviation “IN”. Do this for all other state and DC.</p>
<p>Inside the folder “IN/” there are a geographic header record file named <code>ingeo2010.ur1</code> and 48 data files named as <code>in000012010.ur1</code>, <code>in000022010.ur1</code>, …, <code>in000482010.ur1</code>. The first two characters <code>in</code> is the abbreviation of Indiana. The file extension <code>ur1</code> stands for summary file <strong>1</strong> with <strong>u</strong>rban <strong>r</strong>ural update. The last four numbers <code>2010</code> before file extension indicate the census year 2010. The numbers <code>00001</code>, <code>00002</code>, …, and <code>00048</code> are the sequence of the files. These files are called <code>file 01</code>, <code>file 02</code>, …, and <code>file 48</code> in the <a href="https://www.census.gov/prod/cen2010/doc/sf1.pdf">techinical documentation of the summary file 1</a>. The documentation is our dictionary in using these files and we will talk more about it later.</p>
<p>The geographic header record file <code>ingeo2010.ur1</code> contains the geographic information. It has 331556 lines; each line corresponds to a geographic entity in the census data of Indiana. A geographic entity can be a state, a county, a city, a census tract, a census block etc. A line can be up to 500 characters long, including spaces. Unique to each line is the logical record number, which is 7 characters long, located from 19 to 25 characters in a line. Page 2-8 of the technical documentation lists all geographic field in a line. Each field is assigned with a short reference code. Here are list of frequently use ones:</p>
<table>
<thead>
<tr class="header">
<th>geographic field</th>
<th>reference</th>
<th>starting position</th>
<th>ending position</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>logical record number</td>
<td>LOGRECNO</td>
<td>19</td>
<td>25</td>
</tr>
<tr class="even">
<td>summary level</td>
<td>SUMLEV</td>
<td>9</td>
<td>11</td>
</tr>
<tr class="odd">
<td>geographic component</td>
<td>GEOCOMP</td>
<td>12</td>
<td>13</td>
</tr>
<tr class="even">
<td>county FIPS</td>
<td>COUNTY</td>
<td>30</td>
<td>32</td>
</tr>
<tr class="odd">
<td>place FIPS</td>
<td>PLACE</td>
<td>46</td>
<td>50</td>
</tr>
<tr class="even">
<td>Metropolitan Area FIPS</td>
<td>CBSA</td>
<td>113</td>
<td>117</td>
</tr>
<tr class="odd">
<td>internal point (latitude)</td>
<td>INTPTLAT</td>
<td>337</td>
<td>347</td>
</tr>
<tr class="even">
<td>internal point (longitude)</td>
<td>INTPTLON</td>
<td>348</td>
<td>359</td>
</tr>
</tbody>
</table>
<p>The data files contain the recorded census data. They are <code>.csv</code> files, that is, each data field is separated by a comma. For example, file 02 contains the population in urban and rural area. Its 5th field is the logical record number that matches the geographic header record file. The 6th field is total population, 7th field urban population, 8th field population in urbanized area, … The properties of each field is listed in the technical documentation. If you want to know the details of, for example file 17, just search in the pdf file of the technical documentation for “file 17” and read through the description.</p>
</div>
<div id="extract-the-2010-census-data-step-by-step" class="section level2">
<h2>Extract the 2010 census data step by step</h2>
<p>Say we are interested in the population and race in the city of South Bend, Indiana and we want to plot these data on a map at census block level, what should we do? I will use this as an example to show how to extract 2010 census data in detail.</p>
<div id="read-and-extract-geographic-data" class="section level3">
<h3>read and extract geographic data</h3>
<p>Let’s first take a look at the geographic header record file. We convert it to a data.table of which each row is a line in the file. Each line is a string of characters without separator, so we read it into only one column.</p>
<pre class="r"><code>library(data.table)
# change path to data based on your local directories
geo_file &lt;- fread(paste0(path_to_data, &quot;IN/ingeo2010.ur1&quot;), 
                  sep = &quot;\n&quot;, 
                  header = FALSE)
# show total number of lines
dim(geo_file)</code></pre>
<pre><code>## [1] 331556      1</code></pre>
<pre class="r"><code># display the first line
head(geo_file, 1)</code></pre>
<pre><code>##                                                                                                                                                                                                                                                                                                                                                                                               V1
## 1: UR1ST IN04000000  00000012318                                                                                                                                                                            92789193658    1537004191Indiana                                                                                   AN  6483802  2795541+39.9030256-086.283950300            00448508</code></pre>
<p>This file has 331556 lines. There are many blank spaces in a line as a geographic entity usually does not have all the geographic fields.</p>
<p>We want get the logical record number, which is used to match those in data file, and latitude and longitude for plot in map. We want to keep the FIPS of place so that later on we can locate South Bend city with its FIPS number. We also want keep summary levels as we only want data at census blocks level. The references of geographic fields are used as column names.</p>
<pre class="r"><code>geo &lt;- geo_file[, .(LOGRECNO = as.numeric(substr(V1, 19, 25)),
                    SUMLEV = substr(V1, 9, 11),
                    PLACE = substr(V1, 46, 50),
                    INTPTLAT = as.numeric(substr(V1, 337, 347)),
                    INTPTLON = as.numeric(substr(V1, 348, 359)))]
geo</code></pre>
<pre><code>##         LOGRECNO SUMLEV PLACE INTPTLAT  INTPTLON
##      1:        1    040       39.90303 -86.28395
##      2:        2    040       40.13668 -86.23489
##      3:        3    040       40.43883 -86.21876
##      4:        4    040       40.12984 -86.21021
##      5:        5    040       39.92054 -86.27358
##     ---                                         
## 331552:   331552    970       41.63835 -85.55221
## 331553:   331553    970       41.67686 -87.49205
## 331554:   331554    970       41.15086 -85.66872
## 331555:   331555    970       39.35130 -86.03878
## 331556:   331556    970       41.63419 -87.20929</code></pre>
<p>The column <code>PLACE</code> has a lot of missing values, as many geographic entities does not belong to any place.</p>
<p>Now we can extract geographic data of South Bend. An easy way to find its FIPS number is from <a href="https://en.wikipedia.org/wiki/South_Bend,_Indiana">its Wikipedia page</a>. South Bend’s FIPS is 18-71000. The first two digits are the FIPS of Indiana, so the unique FIPS in Indiana for South Bend is 71000. Let’s keep only the rows for South Bend (sb).</p>
<pre class="r"><code>sb_geo &lt;- geo[PLACE == &quot;71000&quot;]
sb_geo</code></pre>
<pre><code>##       LOGRECNO SUMLEV PLACE INTPTLAT  INTPTLON
##    1:   241621    070 71000 41.61875 -86.24093
##    2:   241622    080 71000 41.63354 -86.22549
##    3:   241623    085 71000 41.63354 -86.22549
##    4:   241624    091 71000 41.63525 -86.21833
##    5:   241625    090 71000 41.63525 -86.21833
##   ---                                         
## 5461:   321382    614 71000 41.72872 -86.26427
## 5462:   324739    624 71000 41.70951 -86.20096
## 5463:   324774    624 71000 41.66799 -86.23096
## 5464:   324810    624 71000 41.66797 -86.27524
## 5465:   324851    624 71000 41.70286 -86.27826</code></pre>
<p>This geographic data includes all summary levels. As we only want the census block level data, we further filter with <code>SUMLEV == &quot;100&quot;</code>. At this stage we get the geographic data we want.</p>
<pre class="r"><code>sb_block &lt;- sb_geo[SUMLEV == &quot;100&quot;]
sb_block</code></pre>
<pre><code>##       LOGRECNO SUMLEV PLACE INTPTLAT  INTPTLON
##    1:   241626    100 71000 41.63613 -86.21864
##    2:   241627    100 71000 41.63670 -86.21659
##    3:   241628    100 71000 41.63573 -86.22172
##    4:   241629    100 71000 41.63182 -86.22022
##    5:   241630    100 71000 41.63367 -86.22093
##   ---                                         
## 5002:   252566    100 71000 41.69486 -86.25132
## 5003:   252567    100 71000 41.69649 -86.25815
## 5004:   253091    100 71000 41.73058 -86.35508
## 5005:   253092    100 71000 41.73035 -86.35565
## 5006:   253093    100 71000 41.72831 -86.35573</code></pre>
<p>Are we sure we get the correct geographic data? We can plot the latitude and longitude directly on a map. From the map below you will also get a sense of what a census block is; it is basically a street block in urban area. We need internet connection to download map data from Google Map.</p>
<pre class="r"><code>library(ggmap)
map &lt;- get_map(&quot;south bend, indiana&quot;, zoom = 13)
ggmap(map) +
    geom_point(data = sb_block, aes(INTPTLON, INTPTLAT), color = &quot;red&quot;, alpha = 0.3)</code></pre>
<p><img src="/post/2017-08-29-process-2010-census-data-with-data-table_files/figure-html/unnamed-chunk-7-1.png" width="768" /></p>
</div>
<div id="read-and-extract-population-and-race-data" class="section level3">
<h3>read and extract population and race data</h3>
<p>From the technical documentation we know that population and race information is in file 03. So let’s read this file.</p>
<pre class="r"><code>f03 &lt;- fread(paste0(path_to_data, &quot;IN/in000032010.ur1&quot;), header = FALSE)</code></pre>
<pre><code>## 
Read 87.5% of 331556 rows
Read 331556 rows and 199 (of 199) columns from 0.134 GB file in 00:00:03</code></pre>
<pre class="r"><code># number of rows and columns
dim(f03)</code></pre>
<pre><code>## [1] 331556    199</code></pre>
<p>It has 199 columns; which ones are what we want? We still go back to the technical documentation, page 6-22, and read the description for file 03. The 5th field is logical record number, 6th the total population data and 8th the black population data. Each population data field also has a reference but is hard to follow. For clarity we name these column in plain English. So all the data we need in Indiana is</p>
<pre class="r"><code>population &lt;- f03[, .(LOGRECNO = V5,
                      total_popul = V6,
                      black_popul = V8)]
population</code></pre>
<pre><code>##         LOGRECNO total_popul black_popul
##      1:        1     6483802      591397
##      2:        2     4697100      580128
##      3:        3     3836584      560288
##      4:        4      860516       19840
##      5:        5     1786702       11269
##     ---                                 
## 331552:   331552       18918          24
## 331553:   331553        4636         154
## 331554:   331554       10537          25
## 331555:   331555         560         100
## 331556:   331556           0           0</code></pre>
<p>From here it is easy to get the population in South Bend at census block level: just join the data to <code>sb_block</code> by logical record number:</p>
<pre class="r"><code>sb_block_popl &lt;- population[sb_block, on = .(LOGRECNO)]
sb_block_popl</code></pre>
<pre><code>##       LOGRECNO total_popul black_popul SUMLEV PLACE INTPTLAT  INTPTLON
##    1:   241626          28          10    100 71000 41.63613 -86.21864
##    2:   241627           0           0    100 71000 41.63670 -86.21659
##    3:   241628          52          16    100 71000 41.63573 -86.22172
##    4:   241629         279          21    100 71000 41.63182 -86.22022
##    5:   241630          42           1    100 71000 41.63367 -86.22093
##   ---                                                                 
## 5002:   252566          64           0    100 71000 41.69486 -86.25132
## 5003:   252567           0           0    100 71000 41.69649 -86.25815
## 5004:   253091           0           0    100 71000 41.73058 -86.35508
## 5005:   253092           0           0    100 71000 41.73035 -86.35565
## 5006:   253093           0           0    100 71000 41.72831 -86.35573</code></pre>
<p>There is no need to keep the blocks where there are no people lives.</p>
<pre class="r"><code>sb_block_popul &lt;- sb_block_popl[total_popul &gt; 0]
sb_block_popul</code></pre>
<pre><code>##       LOGRECNO total_popul black_popul SUMLEV PLACE INTPTLAT  INTPTLON
##    1:   241626          28          10    100 71000 41.63613 -86.21864
##    2:   241628          52          16    100 71000 41.63573 -86.22172
##    3:   241629         279          21    100 71000 41.63182 -86.22022
##    4:   241630          42           1    100 71000 41.63367 -86.22093
##    5:   241631          48           3    100 71000 41.63525 -86.21833
##   ---                                                                 
## 3780:   252543          75           6    100 71000 41.66027 -86.32578
## 3781:   252551          36           0    100 71000 41.69367 -86.24275
## 3782:   252559         360          11    100 71000 41.69560 -86.25924
## 3783:   252561          14           0    100 71000 41.69583 -86.25781
## 3784:   252566          64           0    100 71000 41.69486 -86.25132</code></pre>
</div>
<div id="plot-on-map-at-block-level" class="section level3">
<h3>plot on map at block level</h3>
<p>Now we can plot total and black population on the map. This is the same map we saw at the beginning of the post. It is not shown here.</p>
<pre class="r"><code>ggmap(map) +
    geom_point(data = sb_block_popul, 
               aes(INTPTLON, INTPTLAT, size = total_popul,  color = &quot;red&quot;), 
               alpha = 0.6) +
    # remove row with 0 black population, otherwise show a small dot
    geom_point(data = sb_block_popul[black_popul &gt; 0], 
               aes(INTPTLON, INTPTLAT, size = black_popul, color = &quot;blue&quot;), 
               alpha = 0.6) +
    scale_size_area(breaks = c(1, 50, 100, 300, 600, 1000)) +
    scale_color_identity(guide = &quot;legend&quot;, 
                         breaks = c(&quot;red&quot;, &quot;blue&quot;),
                         label = c(&quot;all&quot;, &quot;black&quot;)) +
    labs(color = &quot;race&quot;, size = &quot;population&quot;) +
    guides(size = guide_legend(override.aes = list(shape = 1)))</code></pre>
</div>
</div>
<div id="more-concise-code" class="section level2">
<h2>More concise code</h2>
<div id="the-data.table-way" class="section level3">
<h3>the data.table way</h3>
<p>The above codes that select South Bend data can be squeezed with pipe operator <code>%&gt;%</code> to get rid of intermediate variables.</p>
<pre class="r"><code>library(data.table)
library(magrittr)

## An example to retrieve and plot the total and black population at the census
## black level of the city South Bend in Indiana

# the directory holding all census 2010 data
path_to_data &lt;- &quot;~/dropbox_datasets/US_2010_census/&quot;

# geographic record of South Bend (sb) at census block level
sb_block &lt;- fread(paste0(path_to_data, &quot;IN/ingeo2010.ur1&quot;), sep = &quot;\n&quot;, 
                  header = FALSE) %&gt;%
    .[, .(LOGRECNO = as.numeric(substr(V1, 19, 25)),
          SUMLEV = substr(V1, 9, 11),
          PLACE = substr(V1, 46, 50),
          INTPTLAT = as.numeric(substr(V1, 337, 347)),
          INTPTLON = as.numeric(substr(V1, 348, 359)))] %&gt;%
    .[PLACE == &quot;71000&quot; &amp; SUMLEV == &quot;100&quot;]

# total and black population of South Bend at census block level
sb_block_popul &lt;- fread(paste0(path_to_data, &quot;IN/in000032010.ur1&quot;), 
                       header = FALSE) %&gt;%
    .[, .(LOGRECNO = V5,
          total_popul = V6,
          black_popul = V8)] %&gt;%
    .[sb_block, on = .(LOGRECNO)] %&gt;%
    .[total_popul &gt; 0]</code></pre>
</div>
<div id="the-dplyr-approach" class="section level3">
<h3>the dplyr approach</h3>
<p>We still use data.table’s <code>fread()</code> to read the data but use dplyr functions to process data.</p>
<pre class="r"><code>library(data.table)
library(dplyr)
path_to_data &lt;- &quot;~/dropbox_datasets/US_2010_census/&quot;

sb_block &lt;- fread(paste0(path_to_data, &quot;IN/ingeo2010.ur1&quot;), sep = &quot;\n&quot;, 
                  header = FALSE) %&gt;%
    transmute(
        LOGRECNO = as.numeric(substr(V1, 19, 25)),
        SUMLEV = substr(V1, 9, 11),
        PLACE = substr(V1, 46, 50),
        INTPTLAT = as.numeric(substr(V1, 337, 347)),
        INTPTLON = as.numeric(substr(V1, 348, 359))
    ) %&gt;%
    filter(PLACE == &quot;71000&quot; &amp; SUMLEV == &quot;100&quot;)

sb_block_popul &lt;- fread(paste0(path_to_data, &quot;IN/in000032010.ur1&quot;), header = FALSE) %&gt;%
    transmute(
        LOGRECNO = V5,
        total_popul = V6,
        black_popul = V8
    ) %&gt;%
    right_join(sb_block, by = &quot;LOGRECNO&quot;) %&gt;%
    filter(total_popul &gt; 0)</code></pre>
</div>
</div>

              
            </div>
          </div>
          <div id="post-footer" class="post-footer main-content-wrap">
            
              
                
                
                  <div class="post-footer-tags">
                    <span class="text-color-light text-small">TAGGED IN</span><br/>
                    
  <a class="tag tag--primary tag--small" href="/tags/data-wrangling/">data wrangling</a>

                  </div>
                
              
            
            
  <div class="post-actions-wrap">
      <nav >
        <ul class="post-actions post-action-nav">
          
            <li class="post-action">
              
                <a class="post-action-btn btn btn--default tooltip--top" href="/2017/09/build-a-r-package-for-yourself/" data-tooltip="Build a R package for yourself">
              
                  <i class="fa fa-angle-left"></i>
                  <span class="hide-xs hide-sm text-small icon-ml">NEXT</span>
                </a>
            </li>
            <li class="post-action">
              
                <a class="post-action-btn btn btn--default tooltip--top" href="/2017/08/place-text-at-right-location/" data-tooltip="ggplot2: place text at right location">
              
                  <span class="hide-xs hide-sm text-small icon-mr">PREVIOUS</span>
                  <i class="fa fa-angle-right"></i>
                </a>
            </li>
          
        </ul>
      </nav>
    <ul class="post-actions post-action-share" >
      
        <li class="post-action hide-lg hide-md hide-sm">
          <a class="post-action-btn btn btn--default btn-open-shareoptions" href="#btn-open-shareoptions">
            <i class="fa fa-share-alt"></i>
          </a>
        </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://www.facebook.com/sharer/sharer.php?u=/2017/08/process-2010-census-data-with-data-table/">
              <i class="fa fa-facebook-official"></i>
            </a>
          </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://twitter.com/intent/tweet?text=/2017/08/process-2010-census-data-with-data-table/">
              <i class="fa fa-twitter"></i>
            </a>
          </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://plus.google.com/share?url=/2017/08/process-2010-census-data-with-data-table/">
              <i class="fa fa-google-plus"></i>
            </a>
          </li>
        
      
      
        <li class="post-action">
          <a class="post-action-btn btn btn--default" href="#disqus_thread">
            <i class="fa fa-comment-o"></i>
          </a>
        </li>
      
      <li class="post-action">
        
          <a class="post-action-btn btn btn--default" href="#">
        
          <i class="fa fa-list"></i>
        </a>
      </li>
    </ul>
  </div>


            
              
                <div id="disqus_thread">
  <noscript>Please enable JavaScript to view the <a href="//disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
</div>
              
            
          </div>
        </article>
        <footer id="footer" class="main-content-wrap">
  <span class="copyrights">
    &copy; 2018 Firstname Lastname. All Rights Reserved
  </span>
</footer>

      </div>
      <div id="bottom-bar" class="post-bottom-bar" data-behavior="4">
        
  <div class="post-actions-wrap">
      <nav >
        <ul class="post-actions post-action-nav">
          
            <li class="post-action">
              
                <a class="post-action-btn btn btn--default tooltip--top" href="/2017/09/build-a-r-package-for-yourself/" data-tooltip="Build a R package for yourself">
              
                  <i class="fa fa-angle-left"></i>
                  <span class="hide-xs hide-sm text-small icon-ml">NEXT</span>
                </a>
            </li>
            <li class="post-action">
              
                <a class="post-action-btn btn btn--default tooltip--top" href="/2017/08/place-text-at-right-location/" data-tooltip="ggplot2: place text at right location">
              
                  <span class="hide-xs hide-sm text-small icon-mr">PREVIOUS</span>
                  <i class="fa fa-angle-right"></i>
                </a>
            </li>
          
        </ul>
      </nav>
    <ul class="post-actions post-action-share" >
      
        <li class="post-action hide-lg hide-md hide-sm">
          <a class="post-action-btn btn btn--default btn-open-shareoptions" href="#btn-open-shareoptions">
            <i class="fa fa-share-alt"></i>
          </a>
        </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://www.facebook.com/sharer/sharer.php?u=/2017/08/process-2010-census-data-with-data-table/">
              <i class="fa fa-facebook-official"></i>
            </a>
          </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://twitter.com/intent/tweet?text=/2017/08/process-2010-census-data-with-data-table/">
              <i class="fa fa-twitter"></i>
            </a>
          </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://plus.google.com/share?url=/2017/08/process-2010-census-data-with-data-table/">
              <i class="fa fa-google-plus"></i>
            </a>
          </li>
        
      
      
        <li class="post-action">
          <a class="post-action-btn btn btn--default" href="#disqus_thread">
            <i class="fa fa-comment-o"></i>
          </a>
        </li>
      
      <li class="post-action">
        
          <a class="post-action-btn btn btn--default" href="#">
        
          <i class="fa fa-list"></i>
        </a>
      </li>
    </ul>
  </div>


      </div>
      <div id="share-options-bar" class="share-options-bar" data-behavior="4">
  <i id="btn-close-shareoptions" class="fa fa-close"></i>
  <ul class="share-options">
    
      <li class="share-option">
        <a class="share-option-btn" target="new" href="https://www.facebook.com/sharer/sharer.php?u=%2F2017%2F08%2Fprocess-2010-census-data-with-data-table%2F">
          <i class="fa fa-facebook-official"></i><span>Share on Facebook</span>
        </a>
      </li>
    
      <li class="share-option">
        <a class="share-option-btn" target="new" href="https://twitter.com/intent/tweet?text=%2F2017%2F08%2Fprocess-2010-census-data-with-data-table%2F">
          <i class="fa fa-twitter"></i><span>Share on Twitter</span>
        </a>
      </li>
    
      <li class="share-option">
        <a class="share-option-btn" target="new" href="https://plus.google.com/share?url=%2F2017%2F08%2Fprocess-2010-census-data-with-data-table%2F">
          <i class="fa fa-google-plus"></i><span>Share on Google&#43;</span>
        </a>
      </li>
    
  </ul>
</div>
<div id="share-options-mask" class="share-options-mask"></div>
    </div>
    
    <div id="about">
  <div id="about-card">
    <div id="about-btn-close">
      <i class="fa fa-remove"></i>
    </div>
    
      <img id="about-card-picture" src="//www.gravatar.com/avatar/d09dc2d7aa5c467519e8af89f7b3d94c?s=110" alt="Author&#39;s picture" />
    
    <h4 id="about-card-name">Firstname Lastname</h4>
    
      <div id="about-card-bio">Super bio with markdown support <strong>COOL</strong></div>
    
    
      <div id="about-card-job">
        <i class="fa fa-briefcase"></i>
        <br/>
        Your job title
      </div>
    
    
      <div id="about-card-location">
        <i class="fa fa-map-marker"></i>
        <br/>
        France
      </div>
    
  </div>
</div>

    <div id="algolia-search-modal" class="modal-container">
  <div class="modal">
    <div class="modal-header">
      <span class="close-button"><i class="fa fa-close"></i></span>
      <a href="https://algolia.com" target="_blank" rel="noopener" class="searchby-algolia text-color-light link-unstyled">
        <span class="searchby-algolia-text text-color-light text-small">by</span>
        <img class="searchby-algolia-logo" src="https://www.algolia.com/static_assets/images/press/downloads/algolia-light.svg">
      </a>
      <i class="search-icon fa fa-search"></i>
      <form id="algolia-search-form">
        <input type="text" id="algolia-search-input" name="search"
          class="form-control input--large search-input" placeholder="Search" />
      </form>
    </div>
    <div class="modal-body">
      <div class="no-result text-color-light text-center">no post found</div>
      <div class="results">
        
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="/2018/02/map-prisons-in-the-united-states/">
                <h3 class="media-heading">Map prisons in the United States</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Feb 2, 2018
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">According to Census 2010, a total number of 2,263,602 persons were incarcerated in the United States. Among them, 172,020 were in federal prisons, 1,248,167 in state prisons, and 682,043 in local jails. Despite 1 in every 110 adults are behind bars, most ordenary people have no idea where are they locked up.
library(totalcensus) library(tidyverse) library(ggmap) # federal and state prison location and population ============================= # search tables for fedral prison search_tablecontents(&quot;decennial&quot;) # PCT0200005 has the total population in federal prison # PCT0200006 has state prison population # read prison population data pris_pop &lt;- read_decennial( year = 2010, states = &quot;US&quot;, table_contents = c( &quot;total = PCT0200003&quot;, &quot;fed_pris = PCT0200005&quot;, &quot;state_pris = PCT0200006&quot;, &quot;local_jail = PCT0200007&quot; ), summary_level = &quot;county subdivision&quot;, show_progress = FALSE ) %&gt;% # remove county subdivisions that has no prison popualation filter(total !</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="/2018/01/the-most-popular-president-lincoln-or-washington/">
                <h3 class="media-heading">Is your town named after Lincoln or Washington?</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Jan 1, 2018
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">Washington and Lincoln are the two greatest presidents in the history of the United States. This post, however, does not discuss how great they are. Instead, I want to show a fun fact related the two presidents: how many cities and towns (and equivalents) are named after them. I am living in Lincoln, Rhode Island, a town so named in honor of President Lincoln.
The data are extracted from decennial census 2010, the most detailed census so far.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="/2018/01/create-pie-plots-on-a-map-in-r/">
                <h3 class="media-heading">Plot pie charts of racial composition in largest metro areas on a map in R</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Jan 1, 2018
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">Pie chart has been criticized for being a poor visualization and is not recommended in R community. The popular ggplot2 package discourages the use of pie charts and there is no dedicated geom_pie for it.
Although the criticism is mostly valid, there is a case that pie chart can be useful: pie charts on maps. Pie charting on map is a compact way to show composition by locations.
A recent R package, scatterpie by Guangchuang Yu, specializes in making pie charts at multiple locations.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="/2017/12/use-totalcensus-package-to-determine-relationship-between-geographic-entities/">
                <h3 class="media-heading">Determine relationship between census geographic entities with totalcensus package</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Dec 12, 2017
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">This is an application example of totalcensus package.
The geographic hierarchy primer in Census 2010 summary file 1 technical documentation displays the relationship between geographic entities. The lower one of the two entities connected by a line is entirely within the boundary of the upper one. For example, a county subdivision is always within the boundaries of a county and a school district always within the boundaries of a state. If two entities are not connected, they may not belong to each other.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="/2017/12/census_data_zip_code/">
                <h3 class="media-heading">Proccess 5-digit ZIP Code Tabulation Area (ZCTA5) data with totalcensus package</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Dec 12, 2017
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">This is an example of applications of totalcensus package. To install the package, follow the instructions at https://github.com/GL-Li/totalcensus.
In this example, we examine data related to 5-digit ZIP Code Tabulation Area (ZCTA5), using 2016 ACS 5-year survey summary files. Let’s first load the libraries and then answer a couple questions related to zip code
library(totalcensus) library(data.table) library(magrittr) library(ggplot2) library(ggmap) What’s the population in a ZCTA5 These population data can be easily obtained with the code below.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="/2017/09/build-a-r-package-for-yourself/">
                <h3 class="media-heading">Build a R package for yourself</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Sep 9, 2017
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">A R user can benefit a lot from building packages. I have read people writing about the benefit in various occasions and cannot agree more after building my first package. We don’t have to a be R developer to write packages. Developers write packages for others; we can just write packages for ourselves. As a R user, we must have written functions and collected datasets, and may have used them across projects or may want to use them later on.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="/2017/08/process-2010-census-data-with-data-table/">
                <h3 class="media-heading">Extract US Census 2010 data with data.table and dplyr</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Aug 8, 2017
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">This post explains how to extract information from the original dataset of the US 2010 census summary file 1 with urban/rural update, using data.table or dplyr package in R.
Why do we want to work with the original data? You may ask, when there are already R packages, such as UScensus2010, censusapi, and tidycensus, which help user get the data.
The biggest benefit is that you will have full access to all the census 2010 data.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="/2017/08/place-text-at-right-location/">
                <h3 class="media-heading">ggplot2: place text at right location</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Aug 8, 2017
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">A common task in plotting is adding texts as labels or annotations to specific locations. ggplot() has functions geom_text(), geom_label() and annotate() for this purpose. In this post we discuss how ggplot2 controls positioning of text.
First we need to specify (x, y) coordinate in the plot where the text is placed. By default, the center of the text is at (x, y), which is sometimes not what we want, as shown in the example below.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="/2017/08/ggplot2-group-overrides-default-grouping/">
                <h3 class="media-heading">ggplot2: aes(group = ...) overrides default grouping</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Aug 8, 2017
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">Default grouping in ggplot2 ggplot2 can subset all data into groups and give each group its own appearance and transformation. In many cases new users are not aware that default groups have been created, and are surprised when seeing unexpected plots.
There are two ways in which ggplot2 creates groups implicitly:
 If x or y are categorical variables, the rows with the same level form a group. Users often overlook this type of default grouping.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="/2017/08/a-uniform-way-to-use-ggplot2/">
                <h3 class="media-heading">My uniform way of using ggplot2</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Aug 8, 2017
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">Just finished reading Hadley Wickham’s ggplot2 book, (second eition). Before that I have been using ggplot2 for a couple of years, mainly learned by reading documentation and searching for help online.
The ggplot2 package is a powerful and comprehensive tool for generating static plots, but I also feel it is a little bit too flexible; the same plot can be made with many different ways. This fexibility provides obvious convenience but also introduces a lot of confusion and extra burden of memorization.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
      </div>
    </div>
    <div class="modal-footer">
      <p class="results-count text-medium"
         data-message-zero="no post found"
         data-message-one="1 post found"
         data-message-other="{n} posts found">
         11 posts found
      </p>
    </div>
  </div>
</div>
    
  
    
    <div id="cover" style="background-image:url('/images/cover.jpg');"></div>
  


    
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js" integrity="sha256-/BfiIkHlHoVihZdc6TFuj7MmJ0TWcWsMXkeDFwhi0zw=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.7/js/jquery.fancybox.min.js" integrity="sha256-GEAnjcTqVP+vBp3SSc8bEDQqvWAZMiHyUSIorrWwH50=" crossorigin="anonymous"></script>


<script src="/js/script-qi9wbxp2ya2j6p7wx1i6tgavftewndznf4v0hy2gvivk1rxgc3lm7njqb6bz.min.js"></script>



<script>
$(document).ready(function() {
  hljs.configure({ classPrefix: '', useBR: false });
  $('pre.code-highlight > code, pre > code').each(function(i, block) {
    if (!$(this).hasClass('codeblock')) {
      $(this).addClass('codeblock');
    }
    hljs.highlightBlock(block);
  });
});
</script>


  
    
      <script>
        var disqus_config = function () {
          this.page.url = '\/2017\/08\/process-2010-census-data-with-data-table\/';
          
            this.page.identifier = '\/2017\/08\/process-2010-census-data-with-data-table\/'
          
        };
        (function() {
          
          
          if (window.location.hostname == "localhost") {
            return;
          }
          var d = document, s = d.createElement('script');
          var disqus_shortname = 'hugo-tranquilpeak-theme';
          s.src = '//' + disqus_shortname + '.disqus.com/embed.js';

          s.setAttribute('data-timestamp', +new Date());
          (d.head || d.body).appendChild(s);
        })();
      </script>
    
  



    
  </body>
</html>

